# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-06 01:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170906_0905'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='school',
            options={'verbose_name_plural': '\u5b66\u6821'},
        ),
    ]
