# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-06 01:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20170906_0914'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'verbose_name_plural': '\u73ed\u7ea7'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name_plural': '\u5b66\u751f'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name_plural': '\u6559\u5e08'},
        ),
    ]
